math(EXPR OPENDCC_VERSION
     "${PROJECT_VERSION_MAJOR} * 10000 + ${PROJECT_VERSION_MINOR} * 100 + ${PROJECT_VERSION_PATCH}")
set(OPENDCC_VERSION_STRING
    "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.${PROJECT_VERSION_TWEAK}")

set(OPENDCC_VERSION_STRING ${OPENDCC_VERSION_STRING})
configure_file(${PROJECT_SOURCE_DIR}/src/lib/opendcc/opendcc.h.in ${PROJECT_BINARY_DIR}/include/opendcc/opendcc.h)
include_directories(${PROJECT_BINARY_DIR}/include)
install(FILES ${PROJECT_BINARY_DIR}/include/opendcc/opendcc.h DESTINATION include/opendcc)
