
[[native.load]]
path='lib/${LIB_PREFIX}cairo${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}cdt${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}cgraph${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}gvc${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}gvplugin_core${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}gvplugin_dot_layout${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}gvplugin_gdiplus${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}gvplugin_neato_layout${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}gvplugin_pango${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}pango-1${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}pangocairo-1${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}pangoft2-1${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}pathplan${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}pixman-1${LIB_EXT}'

[[native.load]]
path='lib/${LIB_PREFIX}xdot${LIB_EXT}'